use_frameworks!

platform :ios, '9.0'

target 'HZSSwizzleMethodTool_Example' do
  pod 'HZSSwizzleMethodTool', :path => '../'

  target 'HZSSwizzleMethodTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
